LeGourmet/Models/Contact.cs
namespace LeGourmet.Models
{
    public class Contact
    {
        public int ContactId { get; set; }

        public string Name { get; set; }

        public string Email { get; set; }

        public string Message { get; set; }
    }
}

LeGourmet/Models/MenuViewModel.cs
using System.Collections.Generic;


namespace LeGourmet.Models
{
    public class MenuViewModel
    {
        public string MenuTitle { get; set; }
        public List<Recipe> Recipes { get; set; }

        public MenuViewModel()
        {
            this.MenuTitle = "Our Recipes";
        }

    }
}

LeGourmet/Models/Recipe.cs
using System.ComponentModel.DataAnnotations;


namespace LeGourmet.Models
{
    public class Recipe
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }

    }
}

LeGourmet/Controllers/HomeController.cs
using LeGourmet.Models;
using LeGourmet.Services;
using Microsoft.AspNetCore.Mvc;


namespace LeGourmet.Controllers
{
    public class HomeController : Controller
    {
        private readonly IContactRepository _contactRepository;

        public HomeController(IContactRepository contactRepository)
        {
            _contactRepository = contactRepository;
        }


        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Index(Contact contact)
        {
            if (ModelState.IsValid && contact != null)
            {
                _contactRepository.AddContact(contact);
                return RedirectToAction(nameof(ContactComplete));
            }
            return View(contact);
        }



        public IActionResult ContactComplete(Contact contact)
        {
            return View();
        }
    }
}

LeGourmet/Controllers/MenuController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using LeGourmet.Models;
using LeGourmet.Services;

namespace LeGourmet.Controllers
{
    public class MenuController : Controller
    {


        private readonly IRecipeRepository _recipeRepository;

        public MenuController(IRecipeRepository recipeRepository)
        {
            _recipeRepository = recipeRepository;
        }


        public IActionResult Index()
        {
            var recipes = _recipeRepository.GetAllRecipes().OrderBy(p => p.Id);

            if (recipes != null)
            {
                var menuViewModel = new MenuViewModel()
                {
                    Recipes = recipes.ToList()
                };
                return View(menuViewModel);
            }
            return View();
        }


    }
}

LeGourmet/Views/Home/ContactComplete.cshtml
<!-- NavBar -->
<nav class="navbar navbar-default navbar-fixed-top" style="background-color:white; font-size: 15px; border-bottom-color:whitesmoke; border-bottom:inset;letter-spacing:4px;">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">LeGourmet Catering</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a class="glyphicon glyphicon-home" asp-controller="Home" asp-action="Index">Home</a></li>
            </ul>
        </div>
    </div>
</nav>

<!-- Container (The Header Section) -->
<div class="container-fluid bg-1 text-center" style="padding-top: 200px; padding-bottom: 190px; background-color:cadetblue;color: #ffffff;">
    <h3 class="margin" style="margin-bottom: 45px; font-size:xx-large;">Thank you, we will get in contact soon!</h3>
    <img src="~/images/8.jpg" class="img-responsive img-circle margin" style="display:inline" alt="Meal" width="350" height="350">
    <h3>Have a beautiful day!</h3>
</div>

LeGourmet/Views/Home/Index.cshtml
@model Contact
<!-- Container (The Header Section) -->
<div class="container-fluid" style="width:78%; padding-top:63px;">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">

            <div class="item active">
                <img src="~/images/2.jpg" alt="LeGourmet Catering" style="width:100%;">
                <div class="carousel-caption">
                    <h3>Le Gourmet Catering</h3>
                    <p>We love dessert!</p>
                </div>
            </div>

            <div class="item">
                <img src="~/images/4.jpg" alt="LeGourmet Catering" style="width:100%;">
                <div class="carousel-caption">
                    <h3>Le Gourmet Catering</h3>
                    <p>We love food!</p>
                </div>
            </div>

            <div class="item">
                <img src="~/images/25.jpg" alt="LeGourmet Catering" style="width:100%;">
                <div class="carousel-caption">
                    <h3>Le Gourmet Catering</h3>
                    <p>We love soup!</p>
                </div>
            </div>



            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>


<div class="container">
    <!-- Container (The About Catering Section) -->

    <div id="about">
        <h1 class="text-center" style="padding-top: 70px;">About Catering</h1>
        <br />
        <p style="font-size:large" class="text-center"><em>Tradition since 2001</em></p>
        <p style="font-size:medium" class="text-center">
            The Catering was founded in Cluj-Napoca by Oana Ujica.
            Delicious catering for every occasion LeGourmet is one of the finest caterers in Cluj-Napoca. We are a family run restaurant that has built an excellent reputation for our delicious food.
            Tickle your taste buds with flavours from around the world in the city of Cluj-Napoca. Business lunch and large order can now be order the same day delivery.
            Event catering must be ordered with at least a week’s notice. Get in touch with one of our team members. We understand how important your special event is to you and we have a reputation for on-time delivery, attention to detail and excellent customer service.
            With over 16 years in this business, we specialise in event catering and business lunch delivery. <a href="#contact">Contact us</a> for further details.
        </p>
        <br>
        <div class="row">
            <div class="container text-center" style="padding:40px 80px; padding-bottom:100px;">
                <div class="col-sm-4">
                    <p class="text-center"><strong>Soup</strong></p><br>
                    <a href="#demo3" data-toggle="collapse">
                        <img src="~/images/5.jpg" class="img-circle person" alt="Soup" width="255" height="255">
                    </a>
                    <div id="demo3" class="collapse">
                        <p>Soup Cream</p>
                        <p>Mushrooms</p>
                        <p>Parsley</p>
                    </div>
                </div>
                <div class="col-sm-4">
                    <p class="text-center"><strong>Cake</strong></p><br>
                    <a href="#demo" data-toggle="collapse">
                        <img src="~/images/6.png" class="img-circle person" alt="Cake" width="255" height="255">
                    </a>
                    <div id="demo" class="collapse">
                        <p>Cake</p>
                        <p>Raspberry</p>
                        <p>Cheesecake</p>
                    </div>
                </div>
                <div class="col-sm-4">
                    <p class="text-center"><strong>Main course</strong></p><br>
                    <a href="#demo2" data-toggle="collapse">
                        <img src="~/images/7.jpg" class="img-circle person" alt="Main Course" width="255" height="255">
                    </a>
                    <div id="demo2" class="collapse">
                        <p>Breakfast</p>
                        <p>Eggs</p>
                        <p>Smoothies</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Container (Menu Section) -->


<div class="container">
    <hr />
    <div>
        <div id="menu">
            <h1 class="text-center" style="padding-top:70px;">Our Menu</h1>
            <br />
            <p class="text-center" style="font-size:large; color:darkcyan">Please click on the image if you want to visualize our full menu.</p>
            <div class="row">
                <div>
                    <div class="text-center">
                        <a asp-controller="Menu" asp-action="Index">
                            <img src="~/images/8.jpg" alt="Cake" class="btn; img-responsive" style="padding:0px 160px; padding-bottom:100px;" />
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Container (Contact Section) -->
<div class="container" style="padding-bottom:40px;">
    <hr>
    <div id="contact">
        <h1 class="text-center" style="padding-top: 70px;">Contact</h1>
        <br />
        <p style="font-size:large; color:darkcyan">We offer full-service catering for any event, large or small. We understand your needs and we will cater the food to satisfy the biggerst criteria of them all, both look and taste.</p>
        <p style="font-size:large; color:darkcyan">Do not hesitate to contact us.</p>
        <br /><br />
        <div class="row">
            <div class="col-md-4">
                <p>Interested? Drop a note.</p>
                <p><span class="glyphicon glyphicon-map-marker"></span>Cluj-Napoca, RO</p>
                <p><span class="glyphicon glyphicon-phone"></span>Phone: +04 0744102720</p>
                <p><span class="glyphicon glyphicon-envelope"></span>Email: oana.m.ujica@gmail.com</p>
            </div>

            <form asp-action="Index" method="post" role="form">
                <div class="col-md-8">
                    <div class="row">
                        <div class="col-sm-6 form-group">
                            <input class="form-control" asp-for="Name" placeholder="Name" type="text" required>
                        </div>
                        <div class="col-sm-6 form-group">
                            <input class="form-control" asp-for="Email" placeholder="Email" type="email" required>
                        </div>
                    </div>
                    <div>
                        <textarea class="form-control" asp-for="Message" placeholder="Message\Special requirement" rows="5" required></textarea>
                    </div>

                    <br>
                    <div class="row">
                        <div class="col-md-12 form-group">
                            <button class="btn pull-right button1" type="submit">Send Message</button>
                        </div>
                    </div>
                </div>
            </form>

        </div>
        <br>
    </div>

    <!-- Image of location/map (Google Maps Section) -->
    <br>
    <div id="map" style="width:100%; height:360px;"></div>

    <script>
        function myMap() {
            var mapCanvas = document.getElementById("map");
            var mapOptions = {
                center: new google.maps.LatLng(46.765850, 23.553433), zoom: 10
            };
            var map = new google.maps.Map(mapCanvas, mapOptions);
        }
    </script>

    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBR7YsKYn9RyEi-J9y0t1EEZqe_0-KehXA&callback=myMap"
            type="text/javascript"></script>

</div>

LeGourmet/Views/Menu/Index.cshtml
@model MenuViewModel
<!-- NavBar -->
<nav class="navbar navbar-default navbar-fixed-top" style="background-color:white; font-size: 15px; border-bottom-color:whitesmoke; border-bottom:inset;letter-spacing:4px;">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">LeGourmet Catering</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a class="glyphicon glyphicon-home" asp-controller="Home" asp-action="Index">Home</a></li>
            </ul>
        </div>
    </div>
</nav>


<!-- Container (The Recipes Section) -->
<br /><br /><br />
<div class="container">
    <div class="text-center">
        <h1>@Model.MenuTitle</h1>
    </div>
    <br /><br />

    <div class="row">
        @foreach (var recipe in Model.Recipes)
        {

            <div class="col-md-4">
                <div class="thumbnail">
                    <img src="~/images/@(recipe.ImageUrl).jpg" alt="" style="width:100%">
                    <div class="caption">
                        <h3>@recipe.Name</h3>
                        <p>Description: @recipe.Description</p>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<br /><br />

LeGourmet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>LeGourmet Catering</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="~/content/site.css" type="text/css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body style="font-family:'Times New Roman', Times, serif">

    <!-- NavBar Fixed-Top -->
    <nav class="navbar navbar-default navbar-fixed-top" style="background-color:white; font-size: 17px; border-bottom-color:whitesmoke; border-bottom:inset; letter-spacing:4px;">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">LeGourmet Catering</a>
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#about" class="glyphicon glyphicon-user">About</a></li>
                    <li><a href="#menu" class="glyphicon glyphicon-th">Menu</a></li>
                    <li><a href="#contact" class="glyphicon glyphicon-envelope">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <section id="myPage">
        @RenderBody()
    </section>

    <!-- Footer -->
    <footer class="text-center" style="padding-top:40px;">
        <a class="up-arrow" href="#myPage" data-toggle="tooltip" title="TO TOP">
            <span class="glyphicon glyphicon-chevron-up"></span>
        </a><br><br>
        <p>Made By Oana Ujica: <a href="https://codingwithoana.wordpress.com/" data-toggle="tooltip" title="Visit codingwithoana.wordpress.com" target="_blank">codingwithoana.wordpress.com</a></p>
    </footer>

    <script>
        $(document).ready(function () {
            // Initialize Tooltip
            $('[data-toggle="tooltip"]').tooltip();

            // Add smooth scrolling to footer link
            $(".navbar a, footer a[href='#myPage']").on('click', function (event) {

                // Make sure this.hash has a value before overriding default behavior
                if (this.hash !== "") {

                    // Prevent default anchor click behavior
                    event.preventDefault();

                    // Store hash
                    var hash = this.hash;

                    // Using jQuery's animate() method to add smooth page scroll
                    // The optional number (1000) specifies the number of milliseconds it takes to scroll to the specified area
                    $('html, body').animate({
                        scrollTop: $(hash).offset().top
                    }, 1000, function () {

                        // Add hash (#) to URL when done scrolling (default click behavior)
                        window.location.hash = hash;
                    });
                } // End if
            });
        })
    </script>



</body>
</html>